### ISSUE TITLE
Capture des paquets VOIP via l'API ne marche pas

### ISSUE THREAD

**Issue by julieni** [julieni/ovh-issues#17]
Je veux utiliser l'API pour mettre en place des captures, toujours pour le problème de supervision

J'utilise donc `POST /telephony/{billingAccount}/line/{serviceName}/trafficExtracts`

Si je planifie la capture dans le futur :

> DateStart : 2017-11-22T13:20:00+01:00
> DateEnd : 2017-11-22T17:20:00+01:00

alors j'ai une erreur quand je regarde la tâche avec `POST /telephony/{billingAccount}/line/{serviceName}/trafficExtracts/{id}`

> {
>     fileUrl: ""
>     fileSize: 0
>     status: "error"
>     dateStart: "2017-11-22T13:20:00+01:00"
>     id: 596
>     dateEnd: "2017-11-22T17:20:00+01:00"
> }

Si je mets une date de départ passée :
> DateStart : 2017-11-22T12:20:00+01:00
> DateEnd : 2017-11-22T17:20:00+01:00

alors la capture se fait bien, le status est bien en doing, mais la capture ne dure pas, j'ai eu maximum 640 secondes capturées, et un status "done"

> {
>     fileUrl: https://storage.p19.cloud.ovh.net/v1/....filename=600.cap
>     fileSize: 11550
>     status: "done"
>     dateStart: "2017-11-22T12:00:00+01:00"
>     id: 600
>     dateEnd: "2017-11-22T17:20:00+01:00"
> }

**Comment by bodji** [comment]
trafficExtracts ne fonctionne que dans le passé pour le moment

**Comment by julieni** [comment]
Ok, pour trace, on peut remonter jusqu'à 1 mois d'archive.
